[[collection]]
type = "art"
title = "The Alchemist"
subtitle = "[Brazilian] Paulo Coelho" # optional
link = "https://www.goodreads.com/book/show/18144590-the-alchemist" # optional
img = "/books/the-alchemist.webp"
content = "A young shepherd named Santiago journeys across deserts seeking treasure, guided by omens and destiny. A philosophical tale about dreams, purpose, and following one’s heart."
footer = "★★★★"

[[collection]]
type = "art"
title = "Sapiens: A Brief History of Humankind"
subtitle = "[Israeli] Yuval Noah Harari" # optional
link = "https://www.goodreads.com/book/show/23692271-sapiens"
img = "/books/sapiens.webp"
content = "An exploration of how Homo sapiens evolved from insignificant primates into the dominant species on Earth. Blends history, science, and philosophy to rethink humanity’s story."
footer = "★★★★★"

[[collection]]
type = "art"
title = "1984"
subtitle = "[British] George Orwell" # optional
link = "https://www.goodreads.com/book/show/4865.How_to_Win_Friends_Influence_People" # optional
img = "/books/1984.webp"
content = "In a totalitarian world ruled by constant surveillance, Winston Smith quietly rebels against the Party. A chilling warning about propaganda, control, and loss of freedom."
footer = "★★★★"
